/*
    
*/

--0. Create schema to use --> first create a user named "c##QLBVIEN"
--step 1: check the user whether exists? If yes ==> don't create a new user. Otherwise, create a new user

begin
execute immediate 'drop user c##QLBVIEN cascade';
exception when others then null;
end;
/
--step 2. create a new user in oracle
create user c##QLBVIEN identified by 123;
--step 3. grant priviledges
GRANT create session TO c##QLBVIEN;
GRANT create table TO c##QLBVIEN;
GRANT create view TO c##QLBVIEN;
GRANT create any trigger TO c##QLBVIEN;
GRANT create any procedure TO c##QLBVIEN;
GRANT create sequence TO c##QLBVIEN;
GRANT create synonym TO c##QLBVIEN;
GRANT CONNECT, RESOURCE, DBA TO c##QLBVIEN  WITH ADMIN OPTION;
GRANT COMMENT ANY TABLE TO c##QLBVIEN;

--1. Kiem tra bang co ton tai hay khong? Neu co thi xoa truoc khi tao
begin
execute immediate 'drop table c##QLBVIEN.NHAN_VIEN CASCADE CONSTRAINT';
exception when others then null;
end;
/
begin
execute immediate 'drop table c##QLBVIEN.PHONG_BAN CASCADE CONSTRAINT';
exception when others then null;
end;
/
begin
execute immediate 'drop table c##QLBVIEN.DON_THUOC CASCADE CONSTRAINT';
exception when others then null;
end;
/
begin
execute immediate 'drop table c##QLBVIEN.CT_DON_THUOC CASCADE CONSTRAINT';
exception when others then null;
end;
/
begin
execute immediate 'drop table c##QLBVIEN.THUOC CASCADE CONSTRAINT';
exception when others then null;
end;
/
begin
execute immediate 'drop table c##QLBVIEN.BENH_NHAN CASCADE CONSTRAINT';
exception when others then null;
end;
/
begin
execute immediate 'drop table c##QLBVIEN.DICH_VU_KHAM_BENH CASCADE CONSTRAINT';
exception when others then null;
end;
/
begin
execute immediate 'drop table c##QLBVIEN.KHAM CASCADE CONSTRAINT';
exception when others then null;
end;
/
begin
execute immediate 'drop table c##QLBVIEN.SU_DUNG_DICH_VU CASCADE CONSTRAINT';
exception when others then null;
end;
/
-- 2. Tao bang
CREATE TABLE c##QLBVIEN.PHONG_BAN
(
    PB_ID NUMBER NOT NULL,
    PB_TEN VARCHAR2(50),
    PB_SDT VARCHAR2(10),
    CONSTRAINT PHONGBAN_PK PRIMARY KEY (PB_ID)
);
/
CREATE TABLE c##QLBVIEN.NHAN_VIEN
(
    NV_ID VARCHAR2(10) NOT NULL,
    NV_TEN VARCHAR2(50),
    NV_NAMSINH DATE,
    NV_DIACHI VARCHAR2(50),
    NV_SDT VARCHAR2(10),
    NV_LUONG NUMBER DEFAULT 0 CHECK (NV_LUONG >= 0),
    NV_LUONGCB NUMBER DEFAULT 0 CHECK (NV_LUONGCB >= 0),
    NV_LOAI VARCHAR2(20),
    NV_SONGAYCONG NUMBER,
    NV_PHUCAP NUMBER DEFAULT 0 CHECK(NV_PHUCAP >= 0),
    NV_CONLV CHAR(1) CHECK(NV_CONLV IN ('1','0')),
    NV_PB NUMBER,
    
    CONSTRAINT NHAN_VIEN_PK PRIMARY KEY (NV_ID)
);
/
CREATE TABLE c##QLBVIEN.BENH_NHAN
(
    BN_ID NUMBER NOT NULL,
    BN_TEN VARCHAR2(50),
    BN_NAMSINH DATE,
    BN_DIACHI VARCHAR2(50),
    BN_SDT VARCHAR2(10),
    
    CONSTRAINT BENH_NHAN_PK PRIMARY KEY (BN_ID)
);
/
CREATE TABLE c##QLBVIEN.DICH_VU_KHAM_BENH
(
    DV_ID NUMBER NOT NULL,
    DV_TEN VARCHAR2(50),
    DV_DONGIA NUMBER CHECK(DV_DONGIA > 0),
    DV_PHONG VARCHAR2(100),
    
    CONSTRAINT DICH_VU_KHAM_BENH_PK PRIMARY KEY ( DV_ID)
);
/
CREATE TABLE c##QLBVIEN.THUOC
(
    T_ID NUMBER NOT NULL,
    T_TENTHUOC VARCHAR2(50),
    T_HANG VARCHAR2(50),
    T_DONGIA NUMBER CHECK(T_DONGIA > 0),
    
    CONSTRAINT THUOC_PK PRIMARY KEY (T_ID)
);
/
CREATE TABLE c##QLBVIEN.DON_THUOC
(
    DT_ID NUMBER NOT NULL,
    DT_TONGTIEN NUMBER DEFAULT 0 CHECK(DT_TONGTIEN >= 0),
    DT_GHICHUBS VARCHAR2(50),
    DT_IDKHAM NUMBER,
    
    CONSTRAINT DON_THUOC_PK PRIMARY KEY (DT_ID)
);
CREATE TABLE c##QLBVIEN.CT_DON_THUOC
(
    CTDT_IDDON NUMBER NOT NULL, 
    CTDT_IDTHUOC NUMBER NOT NULL,
    CTDT_SOLUONG NUMBER(3) CHECK (CTDT_SOLUONG > 0), 
    CTDT_DVTINH VARCHAR2(50), 
    CTDT_GIA NUMBER DEFAULT 0 CHECK(CTDT_GIA >=0), 
    CTDT_LIEUDUNG VARCHAR2(50),
    
    CONSTRAINT CT_DON_THUOC_PK PRIMARY KEY (CTDT_IDDON,CTDT_IDTHUOC)
);
/
CREATE TABLE c##QLBVIEN.KHAM
(
    KH_ID NUMBER NOT NULL, 
    KH_TRIEUCHUNG VARCHAR2(50), 
    KH_THOIGIAN DATE, 
    KH_CHANDOAN VARCHAR2(50), 
    KH_TAIKHAM DATE,
    KH_IDBN NUMBER NOT NULL,
    KH_TONGTIEN NUMBER DEFAULT 0,
    KH_BSKHAM VARCHAR2(10) NOT NULL,
    
    CONSTRAINT KHAM_PK PRIMARY KEY (KH_ID)
);
/
CREATE TABLE c##QLBVIEN.SU_DUNG_DICH_VU
(
    
    SDDV_IDDV NUMBER NOT NULL, 
    SDDV_IDKHAM NUMBER NOT NULL,
    SDDV_NGTHUCHIEN VARCHAR2(10) NOT NULL,
    SDDV_THOIGIAN DATE NOT NULL,
    SDDV_CHECK CHAR(1) CHECK(SDDV_CHECK IN ('1','0')),

    CONSTRAINT SUDUNGDV_PK PRIMARY KEY (SDDV_IDDV, SDDV_IDKHAM, SDDV_NGTHUCHIEN, SDDV_THOIGIAN)
);
/
-- 3. Them khoa ngoai
ALTER TABLE c##QLBVIEN.NHAN_VIEN
ADD CONSTRAINT NV_PHONGBAN_FK 
    FOREIGN KEY(NV_PB)
    REFERENCES c##QLBVIEN.PHONG_BAN(PB_ID) 
    ON DELETE CASCADE;
/
ALTER TABLE c##QLBVIEN.DON_THUOC
ADD CONSTRAINT DT_KHAMBENH
    FOREIGN KEY(DT_IDKHAM)
    REFERENCES c##QLBVIEN.KHAM(KH_ID) 
    ON DELETE CASCADE;
/
ALTER TABLE c##QLBVIEN.CT_DON_THUOC
ADD CONSTRAINT CTDTHUOC_DONTHUOC_FK
    FOREIGN KEY(CTDT_IDDON)
    REFERENCES c##QLBVIEN.DON_THUOC(DT_ID) 
    ON DELETE CASCADE;
/
ALTER TABLE c##QLBVIEN.CT_DON_THUOC
ADD CONSTRAINT CTDTHUOC_THUOC_FK
    FOREIGN KEY(CTDT_IDTHUOC)
    REFERENCES c##QLBVIEN.THUOC(T_ID) 
    ON DELETE CASCADE;
/

ALTER TABLE c##QLBVIEN.KHAM
ADD CONSTRAINT KHAM_BENHNHAN_FK
    FOREIGN KEY(KH_IDBN)
    REFERENCES c##QLBVIEN.BENH_NHAN(BN_ID) 
    ON DELETE CASCADE;
/
ALTER TABLE c##QLBVIEN.KHAM
ADD CONSTRAINT KHAM_BSKHAM_FK
    FOREIGN KEY(KH_BSKHAM)
    REFERENCES c##QLBVIEN.NHAN_VIEN(NV_ID) 
    ON DELETE CASCADE;
/
ALTER TABLE c##QLBVIEN.SU_DUNG_DICH_VU
ADD CONSTRAINT SDUNGDV_FK_DICHVU
    FOREIGN KEY(SDDV_IDDV)
    REFERENCES c##QLBVIEN.DICH_VU_KHAM_BENH(DV_ID) 
    ON DELETE CASCADE;
/
ALTER TABLE c##QLBVIEN.SU_DUNG_DICH_VU
ADD CONSTRAINT SDUNGDV_FK_KHAM
    FOREIGN KEY(SDDV_IDKHAM)
    REFERENCES c##QLBVIEN.KHAM(KH_ID) 
    ON DELETE CASCADE;
/
ALTER TABLE c##QLBVIEN.SU_DUNG_DICH_VU
ADD CONSTRAINT SDUNGDV_FK_NGUOITHUCHIEN
    FOREIGN KEY(SDDV_NGTHUCHIEN)
    REFERENCES c##QLBVIEN.NHAN_VIEN(NV_ID) 
    ON DELETE CASCADE;
/


